export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_TRUE = "GET_CONTACTS_TRUE";
export const GET_CONTACTS_FALSE = "GET_CONTACTS_FALSE";

export const CREATE_CONTACT_ADDRESS = "CREATE_CONTACT_ADDRESS";
export const CREATE_CONTACT_ADDRESS_TRUE = "CREATE_CONTACT_ADDRESS_TRUE";
export const CREATE_CONTACT_ADDRESS_FALSE = "CREATE_CONTACT_ADDRESS_FALSE";

export const REMOVE_CONTACT_ADDRESS = "REMOVE_CONTACT_ADDRESS";
export const REMOVE_CONTACT_ADDRESS_TRUE = "REMOVE_CONTACT_ADDRESS_TRUE";
export const REMOVE_CONTACT_ADDRESS_FALSE = "REMOVE_CONTACT_ADDRESS_FALSE";

export const UPDATE_CONTACT_ADDRESS = "UPDATE_CONTACT_ADDRESS";
export const UPDATE_CONTACT_ADDRESS_TRUE = "UPDATE_CONTACT_ADDRESS_TRUE";
export const UPDATE_CONTACT_ADDRESS_FALSE = "UPDATE_CONTACT_ADDRESS_FALSE";
