export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_TRUE = "GET_CONTACTS_TRUE";
export const GET_CONTACTS_FALSE = "GET_CONTACTS_FALSE";

export const CREATE_CONTACT_ADDRESS = "CREATE_CONTACT_ADDRESS";
export const REMOVE_CONTACT_ADDRESS = "REMOVE_CONTACT_ADDRESS";
export const UPDATE_CONTACT_ADDRESS = "UPDATE_CONTACT_ADDRESS";
